# Generated by Django 5.2.1 on 2025-06-05 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_approval_date_loan_approved_by_loan_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Loan', 'verbose_name_plural': 'Loans'},
        ),
        migrations.RemoveField(
            model_name='loan',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='repaid',
        ),
        migrations.AddField(
            model_name='loan',
            name='approved_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the loan was approved.', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the loan funds were disbursed.', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='duration_months',
            field=models.PositiveIntegerField(default=12, help_text='Duration of the loan in months.'),
        ),
        migrations.AddField(
            model_name='loan',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Expected date for full loan repayment.', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.05, help_text='Annual interest rate (e.g., 0.05 for 5%).', max_digits=5),
        ),
        migrations.AddField(
            model_name='loan',
            name='last_repayment_date',
            field=models.DateTimeField(blank=True, help_text='Date of the most recent repayment.', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='lender',
            field=models.ForeignKey(blank=True, help_text='The user or entity providing the loan funds.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_as_lender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='repaid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount repaid so far.', max_digits=18),
        ),
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the loan record was last updated.'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='loan',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin/Staff user who approved the loan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_as_borrower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the loan application was created.'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='purpose',
            field=models.TextField(blank=True, help_text='Purpose of the loan.', null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active Loan'), ('repaid', 'Repaid'), ('overdue', 'Overdue'), ('liquidated', 'Liquidated')], default='pending', max_length=20),
        ),
    ]
