# Generated by Django 5.2.2 on 2025-06-25 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loan_options_remove_loan_approval_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='loan',
            name='collateral_asset_contract_address',
            field=models.CharField(blank=True, help_text='Address of the ERC-20 token used for collateral (e.g., WETH).', max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='contract_address',
            field=models.CharField(blank=True, help_text='Address of the deployed P2PLoan smart contract.', max_length=42, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='deployment_tx_hash',
            field=models.CharField(blank=True, help_text='Transaction hash of contract deployment.', max_length=66, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_tx_hash',
            field=models.CharField(blank=True, help_text='Transaction hash of loan disbursement.', max_length=66, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='liquidation_tx_hash',
            field=models.CharField(blank=True, help_text='Transaction hash of collateral liquidation.', max_length=66, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_asset_contract_address',
            field=models.CharField(blank=True, help_text='Address of the ERC-20 token used for the loan (e.g., DAI).', max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='repayment_tx_hash',
            field=models.CharField(blank=True, help_text='Transaction hash of loan repayment.', max_length=66, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='disbursement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='duration_months',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='last_repayment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lent_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='repaid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved - Awaiting Lender'), ('on_chain_deployed', 'On-Chain Deployed - Awaiting Collateral/Funding'), ('active', 'Active - Loan Disbursed'), ('repaid', 'Repaid'), ('overdue', 'Overdue'), ('rejected', 'Rejected'), ('liquidated', 'Liquidated')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
