# Generated by Django 5.2.2 on 2025-06-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_loan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved - Awaiting Collateral/Funding'), ('active', 'Active - Loan Disbursed'), ('repaid', 'Repaid'), ('overdue', 'Overdue'), ('rejected', 'Rejected'), ('liquidated', 'Liquidated')], default='pending', max_length=30),
        ),
    ]
