# Generated by Django 5.2.1 on 2025-06-05 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('submitted', 'Submitted for Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('resubmit_required', 'Resubmission Required')], default='pending', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('document_type', models.CharField(blank=True, choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('drivers_license', "Driver's License"), ('other', 'Other')], max_length=50, null=True)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('document_front_url', models.URLField(blank=True, help_text='Secure URL to the front side of the identity document.', max_length=500, null=True)),
                ('document_back_url', models.URLField(blank=True, help_text='Secure URL to the back side of the identity document (if applicable).', max_length=500, null=True)),
                ('selfie_url', models.URLField(blank=True, help_text='Secure URL to a selfie or proof-of-life image.', max_length=500, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Submission',
                'verbose_name_plural': 'KYC Submissions',
            },
        ),
    ]
